-- MySQL Script generated by MySQL Workbench
-- 04/17/18 12:12:51
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema ClinicaOdontologica
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `ClinicaOdontologica` ;

-- -----------------------------------------------------
-- Schema ClinicaOdontologica
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ClinicaOdontologica` DEFAULT CHARACTER SET utf8 ;
USE `ClinicaOdontologica` ;

-- -----------------------------------------------------
-- Table `ClinicaOdontologica`.`Persona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ClinicaOdontologica`.`Persona` (
  `idPersona` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NOT NULL,
  `Apellido1` VARCHAR(45) NOT NULL,
  `Apellido2` VARCHAR(45) NOT NULL,
  `FechaNacimiento` DATE NOT NULL,
  PRIMARY KEY (`idPersona`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ClinicaOdontologica`.`TipoTelefono`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ClinicaOdontologica`.`TipoTelefono` (
  `idTipoTelefono` INT NOT NULL AUTO_INCREMENT,
  `Descripcion` VARCHAR(45) NOT NULL,
  `Activo` BIT NOT NULL,
  PRIMARY KEY (`idTipoTelefono`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ClinicaOdontologica`.`Telefono`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ClinicaOdontologica`.`Telefono` (
  `idTelefono` INT NOT NULL AUTO_INCREMENT,
  `Activo` BIT NOT NULL,
  `FechIngresado` DATE NOT NULL,
  `Persona_idPersona` INT NOT NULL,
  `TipoTelefono_idTipoTelefono` INT NOT NULL,
  PRIMARY KEY (`idTelefono`, `Persona_idPersona`),
  INDEX `fk_Telefono_Persona_idx` (`Persona_idPersona` ASC),
  INDEX `fk_Telefono_TipoTelefono1_idx` (`TipoTelefono_idTipoTelefono` ASC),
  CONSTRAINT `fk_Telefono_Persona`
    FOREIGN KEY (`Persona_idPersona`)
    REFERENCES `ClinicaOdontologica`.`Persona` (`idPersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Telefono_TipoTelefono1`
    FOREIGN KEY (`TipoTelefono_idTipoTelefono`)
    REFERENCES `ClinicaOdontologica`.`TipoTelefono` (`idTipoTelefono`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ClinicaOdontologica`.`TipoCorreo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ClinicaOdontologica`.`TipoCorreo` (
  `idTipoCorreo` INT NOT NULL AUTO_INCREMENT,
  `Descripcion` VARCHAR(45) NOT NULL,
  `Activo` BIT NOT NULL,
  PRIMARY KEY (`idTipoCorreo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ClinicaOdontologica`.`Correo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ClinicaOdontologica`.`Correo` (
  `idCorreo` INT NOT NULL AUTO_INCREMENT,
  `Activo` BIT NOT NULL,
  `FechaIngresado` DATE NOT NULL,
  `Persona_idPersona` INT NOT NULL,
  `TipoCorreo_idTipoCorreo` INT NOT NULL,
  PRIMARY KEY (`idCorreo`, `Persona_idPersona`),
  INDEX `fk_Correo_Persona1_idx` (`Persona_idPersona` ASC),
  INDEX `fk_Correo_TipoCorreo1_idx` (`TipoCorreo_idTipoCorreo` ASC),
  CONSTRAINT `fk_Correo_Persona1`
    FOREIGN KEY (`Persona_idPersona`)
    REFERENCES `ClinicaOdontologica`.`Persona` (`idPersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Correo_TipoCorreo1`
    FOREIGN KEY (`TipoCorreo_idTipoCorreo`)
    REFERENCES `ClinicaOdontologica`.`TipoCorreo` (`idTipoCorreo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ClinicaOdontologica`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ClinicaOdontologica`.`Cliente` (
  `idCliente` INT NOT NULL AUTO_INCREMENT,
  `FechaIngresado` DATE NOT NULL,
  `Activo` BIT NOT NULL,
  `Persona_idPersona` INT NOT NULL,
  PRIMARY KEY (`idCliente`),
  INDEX `fk_Cliente_Persona1_idx` (`Persona_idPersona` ASC),
  CONSTRAINT `fk_Cliente_Persona1`
    FOREIGN KEY (`Persona_idPersona`)
    REFERENCES `ClinicaOdontologica`.`Persona` (`idPersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ClinicaOdontologica`.`Dentista`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ClinicaOdontologica`.`Dentista` (
  `idDentista` INT NOT NULL AUTO_INCREMENT,
  `FechaContratado` DATE NOT NULL,
  `Salario` DECIMAL NOT NULL,
  `Activo` BIT NOT NULL,
  `Persona_idPersona` INT NOT NULL,
  PRIMARY KEY (`idDentista`),
  INDEX `fk_Dentista_Persona1_idx` (`Persona_idPersona` ASC),
  CONSTRAINT `fk_Dentista_Persona1`
    FOREIGN KEY (`Persona_idPersona`)
    REFERENCES `ClinicaOdontologica`.`Persona` (`idPersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ClinicaOdontologica`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ClinicaOdontologica`.`Usuario` (
  `idUsuario` INT NOT NULL AUTO_INCREMENT,
  `FechaIngresado` DATE NOT NULL,
  `Clave` VARCHAR(45) NOT NULL,
  `Persona_idPersona` INT NOT NULL,
  PRIMARY KEY (`idUsuario`),
  INDEX `fk_Usuario_Persona1_idx` (`Persona_idPersona` ASC),
  CONSTRAINT `fk_Usuario_Persona1`
    FOREIGN KEY (`Persona_idPersona`)
    REFERENCES `ClinicaOdontologica`.`Persona` (`idPersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ClinicaOdontologica`.`Asistente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ClinicaOdontologica`.`Asistente` (
  `idAsistente` INT NOT NULL AUTO_INCREMENT,
  `Activo` BIT NOT NULL,
  `Salario` DECIMAL NOT NULL,
  `FechaContaratado` DATE NOT NULL,
  `Persona_idPersona` INT NOT NULL,
  PRIMARY KEY (`idAsistente`),
  INDEX `fk_Asistente_Persona1_idx` (`Persona_idPersona` ASC),
  CONSTRAINT `fk_Asistente_Persona1`
    FOREIGN KEY (`Persona_idPersona`)
    REFERENCES `ClinicaOdontologica`.`Persona` (`idPersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ClinicaOdontologica`.`Expediente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ClinicaOdontologica`.`Expediente` (
  `idExpediente` INT NOT NULL AUTO_INCREMENT,
  `Fecha` DATE NOT NULL,
  `SiguienteCita` DATE NOT NULL,
  `Cliente_idCliente` INT NOT NULL,
  `Asistente_idAsistente` INT NOT NULL,
  `Cliente_idCliente1` INT NOT NULL,
  `Dentista_idDentista` INT NOT NULL,
  PRIMARY KEY (`idExpediente`),
  INDEX `fk_Expediente_Asistente1_idx` (`Asistente_idAsistente` ASC),
  INDEX `fk_Expediente_Cliente1_idx` (`Cliente_idCliente1` ASC),
  INDEX `fk_Expediente_Dentista1_idx` (`Dentista_idDentista` ASC),
  CONSTRAINT `fk_Expediente_Asistente1`
    FOREIGN KEY (`Asistente_idAsistente`)
    REFERENCES `ClinicaOdontologica`.`Asistente` (`idAsistente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Expediente_Cliente1`
    FOREIGN KEY (`Cliente_idCliente1`)
    REFERENCES `ClinicaOdontologica`.`Cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Expediente_Dentista1`
    FOREIGN KEY (`Dentista_idDentista`)
    REFERENCES `ClinicaOdontologica`.`Dentista` (`idDentista`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ClinicaOdontologica`.`Diente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ClinicaOdontologica`.`Diente` (
  `idDiente` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NOT NULL,
  `Activo` BIT NOT NULL,
  PRIMARY KEY (`idDiente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ClinicaOdontologica`.`Factura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ClinicaOdontologica`.`Factura` (
  `idFactura` INT NOT NULL AUTO_INCREMENT,
  `Fecha` DATE NOT NULL,
  `Anulada` BIT NOT NULL,
  `Cliente_idCliente` INT NOT NULL,
  `Asistente_idAsistente` INT NOT NULL,
  PRIMARY KEY (`idFactura`),
  INDEX `fk_Factura_Cliente1_idx` (`Cliente_idCliente` ASC),
  INDEX `fk_Factura_Asistente1_idx` (`Asistente_idAsistente` ASC),
  CONSTRAINT `fk_Factura_Cliente1`
    FOREIGN KEY (`Cliente_idCliente`)
    REFERENCES `ClinicaOdontologica`.`Cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Factura_Asistente1`
    FOREIGN KEY (`Asistente_idAsistente`)
    REFERENCES `ClinicaOdontologica`.`Asistente` (`idAsistente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ClinicaOdontologica`.`Servicio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ClinicaOdontologica`.`Servicio` (
  `idServicio` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NOT NULL,
  `Cantidad` INT NOT NULL,
  `Precio` DECIMAL NOT NULL,
  `Activo` BIT NOT NULL,
  `Descripcion` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`idServicio`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ClinicaOdontologica`.`Factura_Detalle`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ClinicaOdontologica`.`Factura_Detalle` (
  `idFactura_Detalle` INT NOT NULL AUTO_INCREMENT,
  `Cantidad` INT NOT NULL,
  `Precio` DECIMAL NOT NULL,
  `Subtotal` DECIMAL NOT NULL,
  `Total` DECIMAL NOT NULL,
  `Factura_idFactura` INT NOT NULL,
  `Servicio_idServicio` INT NOT NULL,
  PRIMARY KEY (`idFactura_Detalle`, `Factura_idFactura`),
  INDEX `fk_Factura_Detalle_Factura1_idx` (`Factura_idFactura` ASC),
  INDEX `fk_Factura_Detalle_Servicio1_idx` (`Servicio_idServicio` ASC),
  CONSTRAINT `fk_Factura_Detalle_Factura1`
    FOREIGN KEY (`Factura_idFactura`)
    REFERENCES `ClinicaOdontologica`.`Factura` (`idFactura`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Factura_Detalle_Servicio1`
    FOREIGN KEY (`Servicio_idServicio`)
    REFERENCES `ClinicaOdontologica`.`Servicio` (`idServicio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ClinicaOdontologica`.`Protesis`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ClinicaOdontologica`.`Protesis` (
  `idProtesis` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NOT NULL,
  `Activo` BIT NOT NULL,
  PRIMARY KEY (`idProtesis`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ClinicaOdontologica`.`TrabajoRealizado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ClinicaOdontologica`.`TrabajoRealizado` (
  `idTrabajoRealizado` INT NOT NULL AUTO_INCREMENT,
  `Tratamiento` VARCHAR(45) NOT NULL,
  `Diente_idDiente` INT NOT NULL,
  `Protesis_idProtesis` INT NOT NULL,
  `Expediente_idExpediente` INT NOT NULL,
  PRIMARY KEY (`idTrabajoRealizado`, `Expediente_idExpediente`),
  INDEX `fk_TrabajoRealizado_Diente1_idx` (`Diente_idDiente` ASC),
  INDEX `fk_TrabajoRealizado_Protesis1_idx` (`Protesis_idProtesis` ASC),
  INDEX `fk_TrabajoRealizado_Expediente1_idx` (`Expediente_idExpediente` ASC),
  CONSTRAINT `fk_TrabajoRealizado_Diente1`
    FOREIGN KEY (`Diente_idDiente`)
    REFERENCES `ClinicaOdontologica`.`Diente` (`idDiente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TrabajoRealizado_Protesis1`
    FOREIGN KEY (`Protesis_idProtesis`)
    REFERENCES `ClinicaOdontologica`.`Protesis` (`idProtesis`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TrabajoRealizado_Expediente1`
    FOREIGN KEY (`Expediente_idExpediente`)
    REFERENCES `ClinicaOdontologica`.`Expediente` (`idExpediente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
